version = 0.1

[default.deploy.parameters]
stack_name = "prompt-cv-auth"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
template_file = "template-auth.yaml"
resolve_s3 = true
