import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROD_STACK = 'prompt-cv';
const AUTH_STACK = 'prompt-cv-auth';
const REGION = process.env.AWS_REGION || execSync('aws configure get region').toString().trim() || 'eu-central-1';
const DIST_DIR = 'dist/prompt-cv-frontend/browser';

function getStackOutputs(stackName) {
  const raw = execSync(
    `aws cloudformation describe-stacks --stack-name ${stackName} --region ${REGION} --query "Stacks[0].Outputs" --output json`,
    { encoding: 'utf-8' },
  );
  const outputs = JSON.parse(raw);
  return Object.fromEntries(outputs.map((o) => [o.OutputKey, o.OutputValue]));
}

// 1. Fetch stack outputs
console.log('Fetching stack outputs...');
const prodOutputs = getStackOutputs(PROD_STACK);
const authOutputs = getStackOutputs(AUTH_STACK);

const apiUrl = prodOutputs.ApiEndpoint;
const authApiUrl = authOutputs.AuthApiEndpoint;
const bucket = prodOutputs.FrontendBucketName;
const frontendUrl = prodOutputs.FrontendUrl;

if (!apiUrl || !authApiUrl) {
  console.error('Could not discover API URLs from stack outputs. Deploy backend and auth stacks first.');
  process.exit(1);
}
if (!bucket) {
  console.error('FrontendBucketName not found in stack outputs. Deploy the backend first.');
  process.exit(1);
}

// 2. Write environment.prod.ts with discovered URLs
const envPath = resolve(__dirname, '../src/environments/environment.prod.ts');
const envContent = `// Auto-generated by deploy.js — do not edit manually
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  authApiUrl: '${authApiUrl}',
};
`;
writeFileSync(envPath, envContent);
console.log(`Wrote API URLs to environment.prod.ts`);
console.log(`  apiUrl: ${apiUrl}`);
console.log(`  authApiUrl: ${authApiUrl}`);

// 3. Build
console.log('Building frontend...');
execSync('npm run build', { stdio: 'inherit' });

// 4. Upload to S3
console.log(`Uploading to s3://${bucket}...`);
execSync(`aws s3 sync ${DIST_DIR} s3://${bucket} --delete --region ${REGION}`, { stdio: 'inherit' });

// 5. Invalidate CloudFront cache
const distributionId = JSON.parse(
  execSync(
    `aws cloudformation describe-stack-resources --stack-name ${PROD_STACK} --region ${REGION} --query "StackResources[?LogicalResourceId=='FrontendDistribution'].PhysicalResourceId" --output json`,
    { encoding: 'utf-8' },
  ),
)[0];

if (distributionId) {
  console.log(`Invalidating CloudFront cache (${distributionId})...`);
  execSync(`aws cloudfront create-invalidation --distribution-id ${distributionId} --paths "/*" --region ${REGION}`, {
    stdio: 'inherit',
  });
}

console.log(`\nDeploy complete!`);
console.log(`Frontend URL: ${frontendUrl}`);
