// Auto-generated by deploy.js — do not edit manually
export const environment = {
  production: true,
  apiUrl: 'https://e2vieqrvob.execute-api.eu-central-1.amazonaws.com',
  authApiUrl: 'https://8ethu1i40c.execute-api.eu-central-1.amazonaws.com',
};
